[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "none"
padding = { x = 0, y = 0 } 
dynamic_padding = true

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
